# Generated by Django 3.2 on 2022-06-25 12:24

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('female', '0002_femalehomeslider_femalehomeslidertranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FemaleHomeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='home/icons//', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Home Department',
                'verbose_name_plural': 'Home Departments',
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='femalehomepageseo',
            options={'verbose_name': 'Home SEO', 'verbose_name_plural': 'Home SEO'},
        ),
        migrations.AlterModelOptions(
            name='femalehomepageseotranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Home SEO Translation'},
        ),
        migrations.AlterModelOptions(
            name='femalehomeslider',
            options={'verbose_name': 'Home Slider', 'verbose_name_plural': 'Home Sliders'},
        ),
        migrations.AlterModelOptions(
            name='femalehomeslidertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Home Slider Translation'},
        ),
        migrations.AlterField(
            model_name='femalehomeslider',
            name='image',
            field=models.ImageField(upload_to='home/slider//', verbose_name='Slider Image'),
        ),
        migrations.AlterField(
            model_name='femalehomeslidertranslation',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='femalehomeslidertranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='FemaleHomeDepartmentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='female.femalehomedepartment')),
            ],
            options={
                'verbose_name': 'Home Department Translation',
                'db_table': 'female_femalehomedepartment_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
