# Generated by Django 3.2 on 2022-06-26 09:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('female', '0008_femaleservicespageseo_femaleservicespageseotranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FemaleServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='female.femaleserviceitem', verbose_name='Related Service')),
            ],
            options={
                'verbose_name': 'Service Frequently Asked Question',
                'verbose_name_plural': 'Service Frequently Asked Questions',
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FemaleServiceFAQTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Answer')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='female.femaleservicefaq')),
            ],
            options={
                'verbose_name': 'Service Frequently Asked Question Translation',
                'db_table': 'female_femaleservicefaq_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
