# Generated by Django 3.2 on 2022-06-26 14:27

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('female', '0009_femaleservicefaq_femaleservicefaqtranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FemaleServiceOurCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services//cases', verbose_name='Service Image')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='female.femaleserviceitem', verbose_name='Related Service')),
            ],
            options={
                'verbose_name': 'Service Our Cases',
                'verbose_name_plural': 'Service Our Cases',
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FemaleServiceOurCasesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitle')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='female.femaleserviceourcases')),
            ],
            options={
                'verbose_name': 'Service Our Cases Translation',
                'db_table': 'female_femaleserviceourcases_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
