# Generated by Django 3.2 on 2022-06-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('female', '0014_auto_20220626_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='femaleblog',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='View Count'),
        ),
    ]
