# Generated by Django 3.2 on 2022-06-29 20:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('female', '0021_auto_20220629_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='femaleservicecategorytranslation',
            name='banner_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Banner Description'),
        ),
    ]
