# Generated by Django 3.2 on 2022-06-30 15:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('female', '0022_femaleservicecategorytranslation_banner_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FemaleBeforeAfterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('in_navbar', models.BooleanField(default=False, verbose_name='Navigasyon içerisinde mi?')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='before_after/category/banner', verbose_name='Banner Görseli')),
                ('image', models.ImageField(blank=True, null=True, upload_to='before_after/category', verbose_name='Kategori Görseli')),
                ('meta_keywords', models.ManyToManyField(blank=True, to='common.Keywords', verbose_name='Meta Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'Before After Category',
                'verbose_name_plural': 'Before After Categories',
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='femalebeforeafteritem',
            name='in_home',
            field=models.BooleanField(default=False, verbose_name='Navigasyon içerisinde mi?'),
        ),
        migrations.AddField(
            model_name='femalebeforeafteritem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='female.femalebeforeaftercategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='FemaleBeforeAfterCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL Uzantısı')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama')),
                ('banner_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Banner Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='female.femalebeforeaftercategory')),
            ],
            options={
                'verbose_name': 'Before After Category Translation',
                'db_table': 'female_femalebeforeaftercategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
