# Generated by Django 3.2 on 2022-07-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('female', '0028_auto_20220710_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femaleblogtranslation',
            name='_banner_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Banner Title'),
        ),
    ]
