# Generated by Django 3.2 on 2022-07-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('female', '0029_alter_femaleblogtranslation__banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='femalehomepageseo',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/seo', verbose_name='About Section Image'),
        ),
        migrations.AddField(
            model_name='femalehomepageseo',
            name='about_youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='About Youtube Link'),
        ),
        migrations.AddField(
            model_name='femalehomepageseo',
            name='howitworks_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/seo', verbose_name='How it works Section Image'),
        ),
        migrations.AddField(
            model_name='femalehomepageseo',
            name='howitworks_youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='About Youtube Link'),
        ),
    ]
