# Generated by Django 3.2 on 2022-09-20 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0001_initial'),
        ('female', '0030_auto_20220710_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='femaleaboutpageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='femalebeforeaftercategory',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='femalebeforeafterpageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='femaleblog',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='femaleblogspageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='femalecontactpageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='femalehomepageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='femalehowitworkspageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='femalekvkkpageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='femalesearchpageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='femaleservicespageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
    ]
