from .common import *
from .home import *
from .about import *
from .services import *
from .howitworks import *
from .before_after import *
from .blog import *
from .contact import *
from .kvkk import *
