# Generated by Django 3.2 on 2022-06-25 06:58

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('male', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaleHomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/slider//', verbose_name='Slider Görseli')),
            ],
            options={
                'verbose_name': 'Anasayfa Slider',
                'verbose_name_plural': 'Anasayfa Sliderları',
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MaleHomeSliderTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Başlık')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='male.malehomeslider')),
            ],
            options={
                'verbose_name': 'Anasayfa Slider Translation',
                'db_table': 'male_malehomeslider_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
