# Generated by Django 3.2 on 2022-06-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('male', '0003_auto_20220625_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malehomedepartment',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='home/icons//', verbose_name='Icon'),
        ),
    ]
