# Generated by Django 3.2 on 2022-06-26 06:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('male', '0005_maleaboutpageseo_maleaboutpageseotranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='maleaboutpageseo',
            name='section_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Section 1 Image'),
        ),
        migrations.AddField(
            model_name='maleaboutpageseo',
            name='section_1_youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='Section 1 Youtube Link'),
        ),
        migrations.AddField(
            model_name='maleaboutpageseotranslation',
            name='section_1_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Section 1 Body'),
        ),
        migrations.AddField(
            model_name='maleaboutpageseotranslation',
            name='section_1_pretitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Section 1 Main Title'),
        ),
        migrations.AddField(
            model_name='maleaboutpageseotranslation',
            name='section_1_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Section 1 Subtitle'),
        ),
        migrations.AddField(
            model_name='maleaboutpageseotranslation',
            name='section_1_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Section 1 Title'),
        ),
        migrations.AlterField(
            model_name='maleaboutpageseo',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/{gender}', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='maleaboutpageseotranslation',
            name='banner_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Banner Description'),
        ),
        migrations.AlterField(
            model_name='maleaboutpageseotranslation',
            name='banner_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Banner Title'),
        ),
    ]
