# Generated by Django 3.2 on 2022-06-26 07:13

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('male', '0006_auto_20220626_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaleServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='services/banner', verbose_name='Banner Image')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Service Image')),
                ('in_home', models.BooleanField(default=False, verbose_name='In home page services section?')),
                ('order', models.IntegerField(default=1, verbose_name='Ordering')),
                ('meta_keywords', models.ManyToManyField(blank=True, to='common.Keywords', verbose_name='Meta Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Service Items',
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='maleaboutpageseotranslation',
            name='section_1_pretitle',
            field=models.CharField(default='About Us', max_length=200, verbose_name='Section 1 Main Title'),
        ),
        migrations.AlterField(
            model_name='maleaboutpageseotranslation',
            name='section_1_title',
            field=models.CharField(default='Welcome To<br><span>Estophia</span>', max_length=200, verbose_name='Section 1 Title'),
        ),
        migrations.CreateModel(
            name='MaleServiceItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('banner_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Banner Description')),
                ('home_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Home Description')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content Body')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='male.maleserviceitem')),
            ],
            options={
                'verbose_name': 'Service Item Translation',
                'db_table': 'male_maleserviceitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
