# Generated by Django 3.2 on 2022-06-26 14:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('male', '0010_maleserviceourcases_maleserviceourcasestranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maleserviceourcasestranslation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
