# Generated by Django 3.2 on 2022-06-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('male', '0016_malekvkkpageseo_malekvkkpageseotranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='malehomeslidertranslation',
            name='redirect_link',
            field=models.URLField(blank=True, null=True, verbose_name='Redirect Link'),
        ),
    ]
