# Generated by Django 3.2 on 2022-07-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('male', '0025_maleblogtranslation_banner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='maleblog',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/banner', verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='maleblogtranslation',
            name='_banner_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='maleblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs', verbose_name='Image'),
        ),
    ]
