# Generated by Django 3.2 on 2022-07-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('male', '0026_auto_20220710_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='maleblogtranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması'),
        ),
        migrations.AddField(
            model_name='maleblogtranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı'),
        ),
    ]
