# Generated by Django 3.2 on 2022-09-20 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0001_initial'),
        ('male', '0029_auto_20220710_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='maleaboutpageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='malebeforeaftercategory',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='malebeforeafterpageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='maleblog',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='maleblogspageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='malecontactpageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='malehomepageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='malehowitworkspageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='malekvkkpageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='malesearchpageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='maleservicespageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
    ]
